# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

jobs: 
 - job: job1
   steps:
    - script: echo Hello, world1
      displayName: 'JOB1'
 - job: job2
   dependsOn: job1
   steps:
    - script: echo Hello, world2
      displayName: 'JOB2'
 - job: job3
   dependsOn: job1
   steps:
    - script: echo Hello, world3
      displayName: 'JOB2'
