# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  jobs: 
   - job: job1
     steps:
      - script: echo Hello, world1
        displayName: 'JOB1'
- stage: DevDeploy
  dependsOn: Build
   - job: job2
     steps:
      - script: echo Hello, world2
        displayName: 'JOB2'
- stage: QADeploy
  dependsOn: Build
   - job: job3
     steps:
      - script: echo Hello, world2
        displayName: 'JOB3'   
- stage: PRODDeploy
  dependsOn: DevDeploy,QADeploy
   - job: job4
     steps:
      - script: echo Hello, world2
        displayName: 'JOB4' 
